BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Product` (
	`ProductId`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Description`	TEXT,
	`Prize`	TEXT,
	`Imgpath`	TEXT,
	`Title`	TEXT
);
CREATE TABLE IF NOT EXISTS `Orderline` (
	`OrderlineId`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`OrderId`	INTEGER,
	`ProductId`	INTEGER,
	FOREIGN KEY(`OrderId`) REFERENCES `Orders`(`OrderId`),
	FOREIGN KEY(`ProductId`) REFERENCES `Product`(`ProductId`)
);
CREATE TABLE IF NOT EXISTS `Orders` (
	`OrderId`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`UserId`	INTEGER,
	FOREIGN KEY(`UserId`) REFERENCES `User`(`UserId`)
);
CREATE TABLE IF NOT EXISTS `User` (
	`UserId`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Navn`	TEXT,
	`Adresse`	TEXT,
	`Postnummer`	TEXT,
	`Telefon`	TEXT,
	`Email`	TEXT,
	`Password`	TEXT
);
COMMIT;
